<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etiqueta[
<!ELEMENT etiqueta (nombre, calle, ciudad, pais, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>



<etiqueta>
<nombre>Pepe Garcia</nombre>
<calle>C/Ronda</calle>
<ciudad>Cordoba</ciudad>
<pais>España</pais>
<codigo>1235</codigo>
</etiqueta>