<!DOCTYPE errores[
<!ELEMENT errores (error+)>
<!ELEMENT error (tipo,cod,descripcion, localizacion)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT cod (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT localizacion (fichero,fila,columna)>
<!ELEMENT fichero (#PCDATA)>
<!ELEMENT fila (#PCDATA)>
<!ELEMENT columna (#PCDATA)>
<!ATTLIST error id ID #REQUIRED>
]>

<errores>
    <error id="id1">
       <tipo>Aviso</tipo>
      <cod>000001</cod>
      <descripcion>Fichero</descripcion>
       <localizacion>
       <fichero>Ej1.xmlfichero</fichero>
       <fila>3</fila>
      <columna>5</columna>
    </localizacion>
   </error>
   <error id="id2">
       <tipo>Fatal</tipo>
      <cod>100001</cod>
      <descripcion>Error Fatal</descripcion>
       <localizacion>
       <fichero>Error 2</fichero>
       <fila>4</fila>
      <columna>8</columna>
    </localizacion>
   </error>
  
</errores>